# $schema: ./config-schema.json

title: PoCoPI
description: Proof of Concept of Psycho-Informatics.

preTestForm:
  questions:
    - category: Demographic
      text: Multiple selection question
      type: select-multiple
      options:
        - text: Option 1
        - text: Option 2
        - text: Option 3
        - text: Option 4
        - text: Option 5
      min: 1
      max: 3
    - category: Demographic
      text: Single choice question
      type: select-one
      options:
        - text: Option 1
        - text: Option 2
        - text: Option 3
        - text: Option 4
        - text: Option 5
    - category: GRIT-S
      text: Number input
      type: number
      placeholder: Answer here
      min: 1
      max: 2
      step: 0.1
    - category: GRIT-S
      text: Slider question
      type: slider
      min: 1
      max: 10
      step: 1
    - category: SRL
      text: Short text question
      type: text-short
      placeholder: Answer here
      minLength: 1
      maxLength: 50
    - category: TPB
      text: Long text question
      type: text-long
      placeholder: Answer here
      minLength: 1
      maxLength: 400

postTestForm:
  questions:
    - category: GRIT-S
      text: Multiple selection question
      type: select-multiple
      options:
        - text: Option 1
        - text: Option 2
        - text: Option 3
        - text: Option 4
        - text: Option 5
      min: 1
      max: 3
    - category: GRIT-S
      text: Single choice question
      type: select-one
      options:
        - text: Option 1
        - text: Option 2
        - text: Option 3
        - text: Option 4
        - text: Option 5
    - category: SRL
      text: Number input
      type: number
      placeholder: Answer here
      min: 1
      max: 2
      step: 0.1
    - category: SRL
      text: Slider question
      type: slider
      min: 1
      max: 10
      step: 1
    - category: TPB
      text: Short text question
      type: text-short
      placeholder: Answer here
      minLength: 1
      maxLength: 50
    - category: TPB
      text: Long text question
      type: text-long
      placeholder: Answer here
      minLength: 1
      maxLength: 400

groups:
  control:
    probability: 0.3
    protocol: control
  groupA:
    probability: 0.5
    protocol: groupA
  groupB:
    probability: 0.15
    protocol: groupB
  groupC:
    probability: 0.05
    protocol: groupC

protocols:
  control:
    phases:
      - control-phase1
      - questions:
          - image:
              src: control3.webp
              alt: question image
            options:
              - image:
                  src: control3_option1.webp
                  alt: option 1
              - image:
                  src: control3_option2.webp
                  alt: option 2
              - image:
                  src: control3_option3.webp
                  alt: option 3
                correct: true
              - image:
                  src: control3_option4.webp
                  alt: option 4
              - image:
                  src: control3_option5.webp
                  alt: option 5
              - image:
                  src: control3_option6.webp
                  alt: option 6
          - image:
              src: control4.webp
              alt: question image
            options:
              - image:
                  src: control4_option1.webp
                  alt: option 1
              - image:
                  src: control4_option2.webp
                  alt: option 2
              - image:
                  src: control4_option3.webp
                  alt: option 3
              - image:
                  src: control4_option4.webp
                  alt: option 4
                correct: true
              - image:
                  src: control4_option5.webp
                  alt: option 5
              - image:
                  src: control4_option6.webp
                  alt: option 6
  groupA:
    phases:
      - questions:
          - image:
              src: groupA1.webp
              alt: question image
            options:
              - image:
                  src: groupA1_option1.webp
                  alt: option 1
                correct: true
              - image:
                  src: groupA1_option2.webp
                  alt: option 2
              - image:
                  src: groupA1_option3.webp
                  alt: option 3
              - image:
                  src: groupA1_option4.webp
                  alt: option 4
              - image:
                  src: groupA1_option5.webp
                  alt: option 5
              - image:
                  src: groupA1_option6.webp
                  alt: option 6
          - image:
              src: groupA2.webp
              alt: question image
            options:
              - image:
                  src: groupA2_option1.webp
                  alt: option 1
              - image:
                  src: groupA2_option2.webp
                  alt: option 2
                correct: true
              - image:
                  src: groupA2_option3.webp
                  alt: option 3
              - image:
                  src: groupA2_option4.webp
                  alt: option 4
              - image:
                  src: groupA2_option5.webp
                  alt: option 5
              - image:
                  src: groupA2_option6.webp
                  alt: option 6
      - questions:
          - image:
              src: groupA3.webp
              alt: question image
            options:
              - image:
                  src: groupA3_option1.webp
                  alt: option 1
              - image:
                  src: groupA3_option2.webp
                  alt: option 2
              - image:
                  src: groupA3_option3.webp
                  alt: option 3
                correct: true
              - image:
                  src: groupA3_option4.webp
                  alt: option 4
              - image:
                  src: groupA3_option5.webp
                  alt: option 5
              - image:
                  src: groupA3_option6.webp
                  alt: option 6
          - image:
              src: groupA4.webp
              alt: question image
            options:
              - image:
                  src: groupA4_option1.webp
                  alt: option 1
              - image:
                  src: groupA4_option2.webp
                  alt: option 2
              - image:
                  src: groupA4_option3.webp
                  alt: option 3
              - image:
                  src: groupA4_option4.webp
                  alt: option 4
                correct: true
              - image:
                  src: groupA4_option5.webp
                  alt: option 5
              - image:
                  src: groupA4_option6.webp
                  alt: option 6
  groupB:
    phases:
      - questions:
          - image:
              src: groupB1.webp
              alt: question image
            options:
              - image:
                  src: groupB1_option1.webp
                  alt: option 1
                correct: true
              - image:
                  src: groupB1_option2.webp
                  alt: option 2
              - image:
                  src: groupB1_option3.webp
                  alt: option 3
              - image:
                  src: groupB1_option4.webp
                  alt: option 4
              - image:
                  src: groupB1_option5.webp
                  alt: option 5
              - image:
                  src: groupB1_option6.webp
                  alt: option 6
          - image:
              src: groupB2.webp
              alt: question image
            options:
              - image:
                  src: groupB2_option1.webp
                  alt: option 1
              - image:
                  src: groupB2_option2.webp
                  alt: option 2
                correct: true
              - image:
                  src: groupB2_option3.webp
                  alt: option 3
              - image:
                  src: groupB2_option4.webp
                  alt: option 4
              - image:
                  src: groupB2_option5.webp
                  alt: option 5
              - image:
                  src: groupB2_option6.webp
                  alt: option 6
      - questions:
          - image:
              src: groupB3.webp
              alt: question image
            options:
              - image:
                  src: groupB3_option1.webp
                  alt: option 1
              - image:
                  src: groupB3_option2.webp
                  alt: option 2
              - image:
                  src: groupB3_option3.webp
                  alt: option 3
                correct: true
              - image:
                  src: groupB3_option4.webp
                  alt: option 4
              - image:
                  src: groupB3_option5.webp
                  alt: option 5
              - image:
                  src: groupB3_option6.webp
                  alt: option 6
          - image:
              src: groupB4.webp
              alt: question image
            options:
              - image:
                  src: groupB4_option1.webp
                  alt: option 1
              - image:
                  src: groupB4_option2.webp
                  alt: option 2
              - image:
                  src: groupB4_option3.webp
                  alt: option 3
              - image:
                  src: groupB4_option4.webp
                  alt: option 4
                correct: true
              - image:
                  src: groupB4_option5.webp
                  alt: option 5
              - image:
                  src: groupB4_option6.webp
                  alt: option 6
  groupC:
    allowPreviousPhase: false
    allowSkipPhase: false
    randomize: true
    phases:
      - allowPreviousQuestion: false
        allowSkipQuestion: false
        randomize: true
        questions:
          - randomize: true
            image:
              src: groupB1.webp
              alt: question image
            options:
              - image:
                  src: groupB1_option1.webp
                  alt: option 1
                correct: true
              - image:
                  src: groupB1_option2.webp
                  alt: option 2
              - image:
                  src: groupB1_option3.webp
                  alt: option 3
              - image:
                  src: groupB1_option4.webp
                  alt: option 4
              - image:
                  src: groupB1_option5.webp
                  alt: option 5
              - image:
                  src: groupB1_option6.webp
                  alt: option 6
          - randomize: true
            image:
              src: groupB2.webp
              alt: question image
            options:
              - image:
                  src: groupB2_option1.webp
                  alt: option 1
                correct: true
              - image:
                  src: groupB2_option2.webp
                  alt: option 2
              - image:
                  src: groupB2_option3.webp
                  alt: option 3
              - image:
                  src: groupB2_option4.webp
                  alt: option 4
              - image:
                  src: groupB2_option5.webp
                  alt: option 5
              - image:
                  src: groupB2_option6.webp
                  alt: option 6
      - allowPreviousQuestion: true
        allowSkipQuestion: true
        randomize: true
        questions:
          - randomize: true
            image:
              src: groupA1.webp
              alt: question image
            options:
              - image:
                  src: groupA1_option1.webp
                  alt: option 1
                correct: true
              - image:
                  src: groupA1_option2.webp
                  alt: option 2
              - image:
                  src: groupA1_option3.webp
                  alt: option 3
              - image:
                  src: groupA1_option4.webp
                  alt: option 4
              - image:
                  src: groupA1_option5.webp
                  alt: option 5
              - image:
                  src: groupA1_option6.webp
                  alt: option 6
          - randomize: true
            image:
              src: groupA2.webp
              alt: question image
            options:
              - image:
                  src: groupA2_option1.webp
                  alt: option 1
                correct: true
              - image:
                  src: groupA2_option2.webp
                  alt: option 2
              - image:
                  src: groupA2_option3.webp
                  alt: option 3
              - image:
                  src: groupA2_option4.webp
                  alt: option 4
              - image:
                  src: groupA2_option5.webp
                  alt: option 5
              - image:
                  src: groupA2_option6.webp
                  alt: option 6
      - control-phase1

phases:
  control-phase1:
    questions:
      - control-phase1-question1
      - image:
          src: control2.webp
          alt: question image
        options:
          - image:
              src: control2_option1.webp
              alt: option 1
          - image:
              src: control2_option2.webp
              alt: option 2
            correct: true
          - image:
              src: control2_option3.webp
              alt: option 3
          - image:
              src: control2_option4.webp
              alt: option 4
          - image:
              src: control2_option5.webp
              alt: option 5
          - image:
              src: control2_option6.webp
              alt: option 6

questions:
  control-phase1-question1:
    image:
      src: control1.webp
      alt: question image
    options:
      - image:
          src: control1_option1.webp
          alt: option 1
        correct: true
      - image:
          src: control1_option2.webp
          alt: option 2
      - image:
          src: control1_option3.webp
          alt: option 3
      - image:
          src: control1_option4.webp
          alt: option 4
      - image:
          src: control1_option5.webp
          alt: option 5
      - image:
          src: control1_option6.webp
          alt: option 6
