# $schema: ./config-schema.json

groups:
  control:
    probability: 0.4
    protocol: control
  groupA:
    probability: 0.3
    protocol: groupA
  groupB:
    probability: 0.3
    protocol: groupB

protocols:
  control:
    phases:
      - img:
          src: control1.webp
          alt: question image
        options:
          - src: control1_option1.webp
            alt: option 1
            correct: true
          - src: control1_option2.webp
            alt: option 2
          - src: control1_option3.webp
            alt: option 3
          - src: control1_option4.webp
            alt: option 4
          - src: control1_option5.webp
            alt: option 5
          - src: control1_option6.webp
            alt: option 6
      - img:
          src: control2.webp
          alt: question image
        options:
          - src: control2_option1.webp
            alt: option 1
          - src: control2_option2.webp
            alt: option 2
            correct: true
          - src: control2_option3.webp
            alt: option 3
          - src: control2_option4.webp
            alt: option 4
          - src: control2_option5.webp
            alt: option 5
          - src: control2_option6.webp
            alt: option 6
      - img:
          src: control3.webp
          alt: question image
        options:
          - src: control3_option1.webp
            alt: option 1
          - src: control3_option2.webp
            alt: option 2
          - src: control3_option3.webp
            alt: option 3
            correct: true
          - src: control3_option4.webp
            alt: option 4
          - src: control3_option5.webp
            alt: option 5
          - src: control3_option6.webp
            alt: option 6
      - img:
          src: control4.webp
          alt: question image
        options:
          - src: control4_option1.webp
            alt: option 1
          - src: control4_option2.webp
            alt: option 2
          - src: control4_option3.webp
            alt: option 3
          - src: control4_option4.webp
            alt: option 4
            correct: true
          - src: control4_option5.webp
            alt: option 5
          - src: control4_option6.webp
            alt: option 6
  groupA:
    phases:
      - img:
          src: groupA1.webp
          alt: question image
        options:
          - src: groupA1_option1.webp
            alt: option 1
            correct: true
          - src: groupA1_option2.webp
            alt: option 2
          - src: groupA1_option3.webp
            alt: option 3
          - src: groupA1_option4.webp
            alt: option 4
          - src: groupA1_option5.webp
            alt: option 5
          - src: groupA1_option6.webp
            alt: option 6
      - img:
          src: groupA2.webp
          alt: question image
        options:
          - src: groupA2_option1.webp
            alt: option 1
          - src: groupA2_option2.webp
            alt: option 2
            correct: true
          - src: groupA2_option3.webp
            alt: option 3
          - src: groupA2_option4.webp
            alt: option 4
          - src: groupA2_option5.webp
            alt: option 5
          - src: groupA2_option6.webp
            alt: option 6
      - img:
          src: groupA3.webp
          alt: question image
        options:
          - src: groupA3_option1.webp
            alt: option 1
          - src: groupA3_option2.webp
            alt: option 2
          - src: groupA3_option3.webp
            alt: option 3
            correct: true
          - src: groupA3_option4.webp
            alt: option 4
          - src: groupA3_option5.webp
            alt: option 5
          - src: groupA3_option6.webp
            alt: option 6
      - img:
          src: groupA4.webp
          alt: question image
        options:
          - src: groupA4_option1.webp
            alt: option 1
          - src: groupA4_option2.webp
            alt: option 2
          - src: groupA4_option3.webp
            alt: option 3
          - src: groupA4_option4.webp
            alt: option 4
            correct: true
          - src: groupA4_option5.webp
            alt: option 5
          - src: groupA4_option6.webp
            alt: option 6
  groupB:
    phases:
      - img:
          src: groupB1.webp
          alt: question image
        options:
          - src: groupB1_option1.webp
            alt: option 1
            correct: true
          - src: groupB1_option2.webp
            alt: option 2
          - src: groupB1_option3.webp
            alt: option 3
          - src: groupB1_option4.webp
            alt: option 4
          - src: groupB1_option5.webp
            alt: option 5
          - src: groupB1_option6.webp
            alt: option 6
      - img:
          src: groupB2.webp
          alt: question image
        options:
          - src: groupB2_option1.webp
            alt: option 1
          - src: groupB2_option2.webp
            alt: option 2
            correct: true
          - src: groupB2_option3.webp
            alt: option 3
          - src: groupB2_option4.webp
            alt: option 4
          - src: groupB2_option5.webp
            alt: option 5
          - src: groupB2_option6.webp
            alt: option 6
      - img:
          src: groupB3.webp
          alt: question image
        options:
          - src: groupB3_option1.webp
            alt: option 1
          - src: groupB3_option2.webp
            alt: option 2
          - src: groupB3_option3.webp
            alt: option 3
            correct: true
          - src: groupB3_option4.webp
            alt: option 4
          - src: groupB3_option5.webp
            alt: option 5
          - src: groupB3_option6.webp
            alt: option 6
      - img:
          src: groupB4.webp
          alt: question image
        options:
          - src: groupB4_option1.webp
            alt: option 1
          - src: groupB4_option2.webp
            alt: option 2
          - src: groupB4_option3.webp
            alt: option 3
          - src: groupB4_option4.webp
            alt: option 4
            correct: true
          - src: groupB4_option5.webp
            alt: option 5
          - src: groupB4_option6.webp
            alt: option 6
