# $schema: ./schemas/forms.json

preTestForm:
  questions:
    - category: Demográfico
      text: ¿Con cuál de las siguientes opciones te identificas?
      type: select-one
      options:
        - text: Femenino
        - text: Masculino
        - text: Prefiero no decirlo
      other: true
    - category: Demográfico
      text: ¿Dónde estás viviendo actualmente en relación con tu lugar de origen?
      type: select-one
      options:
        - text: Vivo en mi región de origen, con mi familia
        - text: Vivo en mi región de origen, de manera independiente
        - text: Vivo fuera de mi región de origen, con familiares
        - text: Vivo fuera de mi región de origen, independientemente
    - category: Demográfico
      type: select-one
      text: ¿Cuál es el nivel máximo de escolaridad de la madre?
      options:
        - text: Educación básica incompleta
        - text: Educación básica completa
        - text: Educación media incompleta
        - text: Educación media completa
        - text: Educación técnica o profesional
        - text: Educación universitaria
    - category: Demográfico
      type: select-one
      text: ¿En qué año académico te encuentras actualmente?
      options:
        - text: Primero
        - text: Segundo
        - text: Tercero
        - text: Cuarto
        - text: Quinto
        - text: Sexto
    - category: Demográfico
      type: select-one
      text: ¿Qué esperas lograr en los próximos 5 años?
      options:
        - text: Post grado profesional
        - text: Post grado académico
        - text: Otra formación profesional
        - text: Desarrollar experiencia laboral
        - text: Empezar mi propio negocio
        - text: Aún no lo sé
    - category: GRIT-S
      type: slider
      text: Los contratiempos me desaniman
      min: 1
      max: 4
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Algo de acuerdo
        4: Totalmente de acuerdo
    - category: GRIT-S
      type: slider
      text: Soy muy trabajador/a
      min: 1
      max: 4
      step: 1 
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Algo de acuerdo
        4: Totalmente de acuerdo
    - category: GRIT-S
      type: slider
      text: Termino siempre todo lo que empiezo
      min: 1
      max: 4
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Algo de acuerdo
        4: Totalmente de acuerdo
    - category: GRIT-S
      type: slider
      text: Soy diligente (es decir, cuidadoso, activo y que ejecuta con celo y exactitud lo que esta a su cargo)
      min: 1
      max: 4
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Algo de acuerdo
        4: Totalmente de acuerdo
    - category: SRL
      type: slider
      text: >
        Hago un plan antes de comenzar a hacer un trabajo escrito. Pienso lo que voy a hacer y lo que necesito para
        conseguirlo.
      min: 1
      max: 5
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Ni acuerdo ni en desacuerdo
        4: Algo de acuerdo
        5: Totalmente de acuerdo
    - category: SRL
      type: slider
      text: >
        Cuando estudio, intento comprender las materias, tomar apuntes, hacer resúmenes, resolver ejercicios, hacer
        preguntas sobre los contenidos.
      min: 1
      max: 5
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Ni acuerdo ni en desacuerdo
        4: Algo de acuerdo
        5: Totalmente de acuerdo
    - category: SRL
      type: slider
      text: >
        Después de terminar un examen parcial / final, lo reviso mentalmente para saber dónde tuve los aciertos y
        errores y, hacerme una idea de la nota que voy a tener.
      min: 1
      max: 5
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Ni acuerdo ni en desacuerdo
        4: Algo de acuerdo
        5: Totalmente de acuerdo
    - category: TPB
      type: slider
      text: Depende de mí o no que tan bien me va en una actividad académica
      min: 1
      max: 7
      step: 1
      labels:
        1: Totalmente en desacuerdo
        7: Totalmente de acuerdo
    - category: TPB
      type: slider
      text: Si quiero puedo completar todas las tareas de las actividades académicas
      min: 1
      max: 7
      step: 1
      labels:
        1: Totalmente en desacuerdo
        7: Totalmente de acuerdo
    - category: TPB
      type: slider
      text: Depende de mí si mantengo al día mis actividades académicas
      min: 1
      max: 7
      step: 1
      labels:
        1: Totalmente en desacuerdo
        7: Totalmente de acuerdo

postTestForm:
  questions:
    - category: GRIT-S
      type: slider
      text: Los contratiempos me desaniman
      min: 1
      max: 4
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Algo de acuerdo
        4: Totalmente de acuerdo
    - category: GRIT-S
      type: slider
      text: Soy muy trabajador/a
      min: 1
      max: 4
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Algo de acuerdo
        4: Totalmente de acuerdo
    - category: GRIT-S
      type: slider
      text: Termino siempre todo lo que empiezo
      min: 1
      max: 4
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Algo de acuerdo
        4: Totalmente de acuerdo
    - category: GRIT-S
      type: slider
      text: Soy diligente (es decir, cuidadoso, activo y que ejecuta con celo y exactitud lo que esta a su cargo)
      min: 1
      max: 4
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Algo de acuerdo
        4: Totalmente de acuerdo
    - category: SRL
      type: slider
      text: >
        Hago un plan antes de comenzar a hacer un trabajo escrito. Pienso lo que voy a hacer y lo que necesito para
        conseguirlo.
      min: 1
      max: 5
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Ni acuerdo ni en desacuerdo
        4: Algo de acuerdo
        5: Totalmente de acuerdo
    - category: SRL
      type: slider
      text: >
        Cuando estudio, intento comprender las materias, tomar apuntes, hacer resúmenes, resolver ejercicios, hacer
        preguntas sobre los contenidos.
      min: 1
      max: 5
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Ni acuerdo ni en desacuerdo
        4: Algo de acuerdo
        5: Totalmente de acuerdo
    - category: SRL
      type: slider
      text: >
        Después de terminar un examen parcial / final, lo reviso mentalmente para saber dónde tuve los aciertos y
        errores y, hacerme una idea de la nota que voy a tener.
      min: 1
      max: 5
      step: 1
      labels:
        1: Totalmente en desacuerdo
        2: Algo en desacuerdo
        3: Ni acuerdo ni en desacuerdo
        4: Algo de acuerdo
        5: Totalmente de acuerdo
    - category: TPB
      type: slider
      text: Depende de mí o no que tan bien me va en una actividad académica
      min: 1
      max: 7
      step: 1
      labels:
        1: Totalmente en desacuerdo
        7: Totalmente de acuerdo
    - category: TPB
      type: slider
      text: Si quiero puedo completar todas las tareas de las actividades académicas
      min: 1
      max: 7
      step: 1
      labels:
        1: Totalmente en desacuerdo
        7: Totalmente de acuerdo
    - category: TPB
      type: slider
      text: Depende de mí si mantengo al día mis actividades académicas
      min: 1
      max: 7
      step: 1
      labels:
        1: Totalmente en desacuerdo
        7: Totalmente de acuerdo
