# $schema: ./schemas/forms.json

preTestForm:
  questions:
    - category: Demographic
      text: Multiple selection question
      type: select-multiple
      options:
        - text: Option 1
        - text: Option 2
        - text: Option 3
        - text: Option 4
        - text: Option 5
      min: 1
      max: 3
      other: true
    - category: Demographic
      text: Single choice question
      type: select-one
      options:
        - text: Option 1
        - text: Option 2
        - text: Option 3
        - text: Option 4
        - text: Option 5
      other: true
    - category: GRIT-S
      text: Number input
      type: number
      placeholder: Answer here
      min: 1
      max: 2
      step: 0.1
    - category: GRIT-S
      text: Slider question
      type: slider
      min: 1
      max: 10
      step: 1
      labels:
        1: Low
        10: High
    - category: SRL
      text: Short text question
      type: text-short
      placeholder: Answer here
      minLength: 1
      maxLength: 50
    - category: TPB
      text: Long text question
      type: text-long
      placeholder: Answer here
      minLength: 1
      maxLength: 400

postTestForm:
  questions:
    - category: GRIT-S
      text: Multiple selection question
      type: select-multiple
      options:
        - text: Option 1
        - text: Option 2
        - text: Option 3
        - text: Option 4
        - text: Option 5
      min: 1
      max: 3
      other: true
    - category: GRIT-S
      text: Single choice question
      type: select-one
      options:
        - text: Option 1
        - text: Option 2
        - text: Option 3
        - text: Option 4
        - text: Option 5
      other: true
    - category: SRL
      text: Number input
      type: number
      placeholder: Answer here
      min: 1
      max: 2
      step: 0.1
    - category: SRL
      text: Slider question
      type: slider
      min: 1
      max: 10
      step: 1
      labels:
        1: Low
        10: High
    - category: TPB
      text: Short text question
      type: text-short
      placeholder: Answer here
      minLength: 1
      maxLength: 50
    - category: TPB
      text: Long text question
      type: text-long
      placeholder: Answer here
      minLength: 1
      maxLength: 400
