# $schema: ./schemas/home.json

icon:
  src: icons/app.png
  alt: App Icon
title: Test de Matrices Progresivas de Raven
subtitle: Instrucciones para completar el Test de Matrices Progresivas de Raven
description: |-
  Este test está diseñado para evaluar tu capacidad de razonamiento lógico y abstracto. A continuación, encontrarás 10
  preguntas tipo matriz, donde deberás identificar el patrón lógico que sigue la secuencia y elegir la opción que
  completa correctamente la figura.

  **¿Qué debes hacer?**

  1. Observa atentamente cada figura incompleta (matriz) presentada en cada ejercicio.

  2. Analiza los patrones o relaciones entre las formas, líneas o símbolos en filas y columnas.

  3. Selecciona, entre las opciones dadas, la que mejor completa la secuencia.

  4. Marca tu respuesta claramente.

  5. No necesitas conocimientos previos ni cálculos matemáticos complejos.

  6. Trabaja de forma individual y en silencio.

  7. Tienes un tiempo total de 20 minutos para responder las 10 preguntas.

  **Consejos:**

  - No te apresures, pero gestiona bien tu tiempo.

  - Si no sabes una respuesta, pasa a la siguiente y vuelve después si te queda tiempo.

  - No hay penalización por errores.

  - Mantén la concentración durante toda la tarea. Este ejercicio evalúa también tu capacidad de mantener el esfuerzo
  ante la dificultad.

  **Información importante:**

  - Los primeros tres ejercicios son únicamente de práctica y no serán considerados, su propósito es ayudarte a
  familiarizarte con el formato y la lógica del test antes de comenzar con los ejercicios experimentales.

  - Los siguientes 10 ejercicios forman parte de la tarea experimental, y tus respuestas serán registradas como parte
  del estudio.

informedConsent: |-
  Al aceptar participar en este estudio, usted reconoce que:

  - Su participación es completamente voluntaria.

  - Los datos proporcionados serán tratados con confidencialidad.

  - La información recopilada se utilizará únicamente con fines académicos.

  - Puede abandonar el examen en cualquier momento si lo desea.

  Si tiene alguna pregunta sobre el estudio, puede comunicarse con el equipo de investigación enviando un correo
  electrónico a [research@example.com](mailto:research@example.com).
